# Generated by Django 5.0.6 on 2024-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meterData',
            fields=[
                ('cumm_energy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('power', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unix_time', models.IntegerField(primary_key=True, serialize=False)),
                ('converted_unixtime', models.DateTimeField()),
                ('meter_reset', models.BooleanField(default=False)),
                ('energy_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
